package(default_visibility = ["//visibility:public"])
load ("//GameLabs/BuildRules/project:ue_project_rules.bzl","build_project")


build_project(
    name="build_me",
    unreal_engine ="@UnrealEngine//:build_ue5" 
    )