workspace(name = "MyWorkspace")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
load ("@bazel_tools//tools/build_defs/repo:git.bzl", "new_git_repository")


new_git_repository(
	name = "UnrealEngine",
	remote = "git@github.com:EpicGames/UnrealEngine.git",
	build_file = "//GameLabs/BuildRules/engine:ue5_engine.BUILD",
	commit = "da3a161677a3f03c509dc7a608f0af73bf0c008b",
	shallow_since = "1648560230 -0400"
	)

http_archive(
    name = "downloaded-python",
    urls = ["https://www.python.org/ftp/python/3.9.10/python-3.9.10-embed-amd64.zip"],
    sha256 = "67161cab713a52f6658b76274f8dbe0cd2f256aab1e84f94cd557d4a906fa5d2",
    build_file = "//:BUILD.downloaded-python"
  )


  new_local_repository(
  	name = "local-ue5",
  	path = "UnrealEngine/"
  	build_file = "//GameLabs/BuildRules/engine:ue5_engine_rules.bzl"
  )