load("//:GameLabs/BuildRules/ue5_rules.bzl", "build_client","build_server")

package(default_visibility = ["//visibility:public"])

build_server(
    name="build-ue5-server",
    srcs = glob(["**/*"]),
    )